# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordid', models.CharField(max_length=20, verbose_name='ID сообщения')),
                ('cnrid', models.CharField(max_length=20, verbose_name='Номер конрагента')),
                ('sibnum', models.CharField(max_length=20, verbose_name='ID входящего ящика')),
                ('sender', models.CharField(max_length=20, verbose_name='Номер отправителя')),
                ('target', models.CharField(max_length=20, verbose_name='Номер получателя')),
                ('rescount', models.SmallIntegerField(verbose_name='Количество')),
                ('text', models.CharField(max_length=500, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name_plural': 'SMS сообщения',
                'verbose_name': 'SMS сообщение',
            },
        ),
    ]
