# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='cnrid',
            new_name='agtid',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='sibnum',
            new_name='inbox',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='ordid',
            new_name='smsid',
        ),
        migrations.AlterField(
            model_name='sms',
            name='text',
            field=models.CharField(max_length=480, verbose_name='Текст сообщения'),
        ),
    ]
