# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20160620_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssended',
            name='delivered',
        ),
        migrations.AddField(
            model_name='smssended',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Успешно'),
        ),
    ]
