# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 04:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20160622_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='ban_date',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 6, 11, 20, 37, 709166), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 6, 11, 20, 50, 797367), verbose_name='Дата последнего запроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя дата обращения'),
        ),
    ]
