# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_smssended_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('account', models.CharField(max_length=12, verbose_name='Лицевой счет')),
                ('blocked', models.BooleanField(verbose_name='Заблокирован')),
                ('ban_date', models.DateField(verbose_name='Дата блокировки')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
            },
        ),
    ]
