# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, verbose_name='Лицевой счет')),
                ('last_date', models.DateField(auto_now_add=True, verbose_name='Последняя дата обращения')),
            ],
            options={
                'verbose_name': 'Лицевой счет',
                'verbose_name_plural': 'Лицевой счет',
            },
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='account',
        ),
        migrations.AddField(
            model_name='smsreceived',
            name='response',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='sms.SmsSended', verbose_name='Ответная смс'),
        ),
        migrations.AddField(
            model_name='smssended',
            name='answer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='sms.SmsReceived', verbose_name='Начальная смс'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='ban_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата блокировки'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Subscriber', verbose_name='Абонент'),
        ),
    ]
