# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20160620_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsreceived',
            name='response',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sms.SmsSended', verbose_name='Ответная смс'),
        ),
        migrations.AlterField(
            model_name='smssended',
            name='answer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sms.SmsReceived', verbose_name='Начальная смс'),
        ),
    ]
