# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_auto_20160620_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscriber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sms.Subscriber', verbose_name='Абонент'),
        ),
    ]
