# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('number', models.CharField(max_length=5, unique=True, verbose_name='Номер')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='Мобильный')),
                ('mac_adress', models.CharField(blank=True, max_length=12, verbose_name='MAC-адрес')),
                ('panel', models.BooleanField(default=False, verbose_name='Панель расширения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='ExtendedNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('number', models.CharField(blank=True, max_length=11, verbose_name='Номер')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phonebook.User')),
            ],
            options={
                'verbose_name': 'Номер на панели',
                'verbose_name_plural': 'Номер на панели',
            },
        ),
        migrations.AlterModelOptions(
            name='extendednumber',
            options={'verbose_name': 'Номер на панели', 'verbose_name_plural': 'Номера на панели'},
        ),
        migrations.AlterField(
            model_name='extendednumber',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.User', verbose_name='Просматривает'),
        ),
        migrations.AddField(
            model_name='extendednumber',
            name='key',
            field=models.PositiveSmallIntegerField(verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='extendednumber',
            name='module',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='extendednumber',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='extendednumber',
            name='number',
            field=models.CharField(max_length=11, verbose_name='Номер'),
        ),
    ]
