# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20160607_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Красэко', (('general', 'Общий'), ('administrator', 'Адиминистративная служба'), ('accounting', 'Бухгалтерия'), ('director', 'Дирекция'), ('engineer', 'Служба главного инженера'), ('secretory', 'Служба делопроизводства'), ('build', 'Служба капитального строительства'), ('law', 'Служба по правовым вопросам'), ('sell', 'Служба реализации услуг'), ('supply', 'Служба снабжения'), ('control', 'Служба финансового контроля'), ('finance', 'Финансово-экономическая служба'))), ('КИЦ', (('kic_general', 'Общий'),)), ('Министерство', (('min_general', 'Общий'),))], default='general', max_length=50, verbose_name='Отдел'),
        ),
    ]
