# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('phonebook', '0001_squashed_0013_auto_20160505_1213'), ('phonebook', '0002_auto_20160530_1048'), ('phonebook', '0003_auto_20160603_1535'), ('phonebook', '0004_auto_20160603_1557'), ('phonebook', '0005_auto_20160607_1314'), ('phonebook', '0006_auto_20160616_1449'), ('phonebook', '0007_auto_20160616_1535'), ('phonebook', '0008_auto_20160616_1543')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('number', models.CharField(max_length=5, unique=True, verbose_name='Номер')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='Мобильный')),
                ('mac_adress', models.CharField(blank=True, max_length=12, verbose_name='MAC-адрес')),
                ('panel', models.BooleanField(default=False, verbose_name='Панель расширения')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='ExtendedNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('number', models.CharField(blank=True, max_length=11, verbose_name='Номер')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phonebook.User')),
            ],
            options={
                'verbose_name_plural': 'Номер на панели',
                'verbose_name': 'Номер на панели',
            },
        ),
        migrations.AlterModelOptions(
            name='extendednumber',
            options={'verbose_name': 'Номер на панели', 'verbose_name_plural': 'Номера на панели'},
        ),
        migrations.AlterField(
            model_name='extendednumber',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.User', verbose_name='Просматривает'),
        ),
        migrations.AddField(
            model_name='extendednumber',
            name='key',
            field=models.PositiveSmallIntegerField(verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='extendednumber',
            name='module',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='extendednumber',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='extendednumber',
            name='number',
            field=models.CharField(max_length=11, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('kraseco', 'Красэко'), ('kic', 'КИЦ'), ('ministry', 'Министерство')], default='kraseco', max_length=50, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Красэко', (('general', 'Общий'), ('administrator', 'Адиминистративная служба'), ('accounting', 'Бухгалтерия'), ('director', 'Дирекция'), ('engineer', 'Служба главного инженера'), ('secretory', 'Служба делопроизводства'), ('build', 'Служба капитального строительства'), ('law', 'Служба по правовым вопросам'), ('sell', 'Служба реализации услуг'), ('supply', 'Служба снабжения'), ('control', 'Служба финансового контроля'), ('finance', 'Финансово-экономическая служба'))), ('КИЦ', (('kic_general', 'Общий'),)), ('Министерство', (('min_general', 'Общий'),))], default='general', max_length=50, verbose_name='Отдел'),
        ),
        migrations.CreateModel(
            name='SideNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('number', models.CharField(max_length=11, verbose_name='Номер')),
            ],
            options={
                'verbose_name_plural': 'Сторонние номера',
                'verbose_name': 'Сторонний номер',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=40, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, default=None, max_length=40, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_mail',
            field=models.BooleanField(default=False, verbose_name='Голосовая почта'),
        ),
    ]
