# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20160530_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('number', models.CharField(max_length=11, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Сторонний номер',
                'verbose_name_plural': 'Сторонние номера',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=' ', max_length=40, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=' ', max_length=40, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('kraseco', 'Красэко'), ('kic', 'КИЦ'), ('ministry', 'Министерство')], default='kraseco', max_length=20, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('general', 'Общий')], default='general', max_length=20, verbose_name='Отдел'),
        ),
    ]
