# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20160603_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='Общий', max_length=50, verbose_name='Отдел'),
        ),
    ]
