# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20160603_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voice_mail',
            field=models.BooleanField(default=False, verbose_name='Голосовая почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('kraseco', 'Красэко'), ('kic', 'КИЦ'), ('ministry', 'Министерство')], default='kraseco', max_length=50, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Красэко', (('general', 'Общий'), ('administrator', 'Адиминистративная служба'), ('accounting', 'Бухгалтерия'), ('director', 'Дирекция'), ('engineer', 'Служба главного инженера'), ('secretory', 'Служба делопроизводства'), ('build', 'Служба капитального строительства'), ('law', 'Служба по правовым вопросам'), ('sell', 'Служба реализации услуг'), ('supply', 'Служба снабжения'), ('control', 'Служба финансового контроля'), ('finance', 'Финансово-экономическая служба'))), ('КИЦ', (('kic_general', 'Общий'),)), ('Министерство', (('min_general', 'Общий'),))], default='Красэко', max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, default=None, max_length=40, verbose_name='Отчество'),
        ),
    ]
